version: '3'

services:
  db:
    image: mariadb:10
    container_name: db_lamp
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root

  web:
    build: . 
    container_name: apache2
    restart: always
    depends_on:
      - db   
    ports:    
      - "80:80"
    volumes:
      - ./www:/var/www/html
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "1200:80"
    links:
      - db:db
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=user

volumes:
  db_data:
